Fix push to new branches
https://github.com/ruby/ruby/actions/runs/20728992203/job/59511845281

```
+ git -C /data/git.ruby-lang.org/update-ruby push origin github/ruby_4_0:ruby_4_0
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'ruby_4_0' on the remote side.
- Checking if the <src> being pushed ('refs/remotes/github/ruby_4_0')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'refs/remotes/github/ruby_4_0:refs/heads/ruby_4_0'?
error: failed to push some refs to 'file:///var/git/ruby.git'
```